CREATE TABLE ITEMS (
    ITEM_I SERIAL,
    SKU TEXT NOT NULL,
    ITEM_DESCRIPTION TEXT DEFAULT '',
    PRICE NUMERIC(5, 2),
    CRTE_TS TIMESTAMPTZ NULL DEFAULT current_timestamp
);

select * from items;